PROJECT = cowboy_server
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy
dep_cowboy_commit = 2.11.0

REL_DEPS = relx # Librería que crea el release

DEP_PLUGINS = cowboy # Importa los plugins de cowboy

include erlang.mk
